install:
	uv sync

build:
	uv build

run:
	uv run gendiff -h
diff:
	uv run gendiff tests/test_files/file3.json tests/test_files/file4.json
diff_json:
	uv run gendiff tests/test_files/file3.json tests/test_files/file4.json -f json
diff_yml:
	uv run gendiff tests/test_files/file3.yml tests/test_files/file4.yml

test:
	uv run pytest

test-coverage:
	uv run pytest --cov=genediff --cov-report xml

lint:
	uv run ruff check

check: test lint