name: my_check
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
        # make depends on uv
      - name: Install dependencies
        run: |
          pip install uv
          make install
          pip install coverage
      - name: Run linter and pytest
        run: |
          make check
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@prefix-support
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true